Feature/add pytest to jenkins
xmos/lib_xud pull request #240
Opened 2021-07-14 10:56 UTC by kevinyeungxmos

2021-07-14 11:10 UTC, xross commented
I would run the tests on a single process until #230 is resolved.

2021-07-14 11:10 UTC, xross requested changes
I would run the tests on a single process until #230 is resolved.

2022-02-01 12:13 UTC, xross commented
@kevinyeungxmos Currently fails with: ModuleNotFoundError: No module named 'filelock'

2022-02-09 09:37 UTC, danielpieczko commented on Jenkinsfile
> +          dir("${REPO}/tests") {
To use the python virtualenv that includes the dependencies in requirements.txt, you need a withVenv() closure here, along with the viewEnv() and dir() you already have.

2022-02-14 09:07 UTC, closed without merging